#
# config.yml
#
# @package Easybash
# @system  Ubuntu 16.04 (Xenial)
# @date    2020/04/22
#
# After completing the following setting, run:
#
#   ./easybash.sh install
#

install:
#   - apache
    - mariadb
#   - mysql
    - nginx
    - php

config:
    #--------------------------------#
    # Apache server                  #
    #---------+----------------------#
    # version | latest: 2.4.41       #
    #         | system: 2.4.18       #
    #---------+----------------------#
    apache:
        name: apache
        version: latest
    #------------------------------------#
    # MariaDB                            #
    #-----------------+------------------#
    # version         | latest: 10.11.2  #
    #                 | system: 10.0.38  #
    #                 | mainline: 11.0.1 #
    # password        | *                #
    # secure          | y, n             #
    # remote          | y, n             #
    # remote_user     | *                #
    # remote_password | *                #
    #-----------------+------------------#
    mariadb:
        name: mariadb
        version: latest
        password: 12345678
        secure: y
        remote: y
        remote_user: test_user
        remote_password: 12345678
    #----------------------------------#
    # MySQL                            #
    #-----------------+----------------#
    # version         | latest: 8.0.25 #
    #                 | system: 5.7.33 #
    # password        | *              #
    # secure          | y, n           #
    # remote          | y, n           #
    # remote_user     | *              #
    # remote_password | *              #
    #-----------------+----------------#
    mysql:
        name: mysql
        version: latest
        password: 12345678
        secure: y
        remote: y
        remote_user: test_user
        remote_password: 12345678
    #--------------------------------#
    # Nginx                          #
    #---------+----------------------#
    # version | latest: 1.24.0       #
    #         | mainline: 1.23.4     #
    #         | system: 1.10.3       #
    #---------+----------------------#
    nginx:
        name: nginx
        version: latest
    #--------------------------------#
    # PHP-FPM                        #
    #---------+----------------------#
    # version | 5.6 - 8.2            #
    # modules | see list             #
    #---------+----------------------#
    php:
        name: "php-fpm"
        version: 8.2
        modules:
            - bcmath
            - bz2
            - cgi
            - cli
            - common
            - curl
            - dba
            - dev
            - enchant
            - gd
            - mp
            - imap
            - imagick
            - interbase
            - intl
            - json
            - ldap
            - mbstring
            - memcached
            - mongodb
            - mysql
            - odbc
            - opcache
            - pgsql
            - phpdbg
            - pspell
            - readline
            - recode
            - redis
            - snmp
            - soap
            - sqlite3
            - sybase
            - tidy
            - xdebug
            - xml
            - xmlrpc
            - xsl
            - zip
