#
# config.yml
#
# @package Easybash
# @system  Ubuntu 18.04 (Bionic)
# @date    2020/04/22
#
# After completing the following setting, run:
#
#   ./easybash.sh install
#

install:
#   - apache
#   - dart
#   - golang
    - mariadb
#   - mysql
    - nginx
#   - nodejs
    - php
    - redis
  
config:
    #--------------------------------#
    # Apache server                  #
    #---------+----------------------#
    # version | latest: 2.4.43       #
    #         | system: 2.4.29       #
    #---------+----------------------#
    apache:
        name: apache
        version: latest
    #-----------------------------------#
    # Dart                              #
    #-----------------+-----------------#
    # version         | latest: 2.7.2   #
    #                 | mainline: 2.9.0 #
    #-----------------+-----------------#
    dart:
        name: dart
        version: latest
    #----------------------------------#
    # Golang                           #
    #-----------------+----------------#
    # version         | latest: 1.14.2 #
    #                 | system: 1.10.4 #
    #-----------------+----------------#
    golang:
        name: golang
        version: latest
    #-----------------------------------#
    # MariaDB                           #
    #-----------------+-----------------#
    # version         | latest: 10.4.12 #
    #                 | system: 10.1.29 #
    #                 | mainline: 10.5  #
    # password        | *               #
    # secure          | y, n            #
    # remote          | y, n            #
    # remote_user     | *               #
    # remote_password | *               #
    #-----------------+-----------------#
    mariadb:
        name: mariadb
        version: latest
        password: 12345678
        secure: y
        remote: y
        remote_user: test_user
        remote_password: 12345678
    #----------------------------------#
    # MySQL                            #
    #-----------------+----------------#
    # version         | latest: 8.0.19 #
    #                 | system: 5.7.29 #
    # password        | *              #
    # secure          | y, n           #
    # remote          | y, n           #
    # remote_user     | *              #
    # remote_password | *              #
    #-----------------+----------------#
    mysql:
        name: mysql
        version: latest
        password: 12345678
        secure: y
        remote: y
        remote_user: test_user
        remote_password: 12345678
    #--------------------------------#
    # Nginx                          #
    #---------+----------------------#
    # version | latest: 1.18.0       #
    #         | mainline: 1.17.10    #
    #         | system: 1.14         #
    #---------+----------------------#
    nginx:
        name: nginx
        version: latest
    #------------------------------------#
    # Nodejs                             #
    #-----------------+------------------#
    # version         | latest: 12.16.2  #
    #                 | mainline: 14.0.0 #
    #                 | system: 8.10.0   #
    #-----------------+------------------#
    nodejs:
        name: nodejs
        version: latest
    #--------------------------------#
    # PHP-FPM                        #
    #---------+----------------------#
    # version | 5.6, 7.0-7.4         #
    # modules | see list             #
    #---------+----------------------#
    php:
        name: "php-fpm"
        version: 7.4
        modules:
            - bcmath
            - bz2
            - cgi
            - cli
            - common
            - curl
            - dba
            - dev
            - enchant
            - gd
            - gmp
            - imap
            - interbase
            - intl
            - json
            - ldap
            - mbstring
            - mysql
            - odbc
            - opcache
            - pgsql
            - phpdbg
            - pspell
            - readline
            - recode
            - redis
            - snmp
            - soap
            - sqlite3
            - sybase
            - tidy
            - xml
            - xmlrpc
            - xsl
            - zip
    #--------------------------------#
    # Redis                          #
    #---------+----------------------#
    # version | latest: 5.0.8        #
    #         | system: 4.0.9        #
    #---------+----------------------#
    redis:
        name: redis
        version: latest

